### ISSUE TITLE
no working link to download the installer

### ISSUE THREAD

**Issue by mrkaban** [maxim-s-barabash/ZebraTrace#3]
no working link to download the installer

**Comment by maxim-s-barabash** [comment]
Thanks, we will fix it now.

I will leave links to the version for windows here:
 - [ZebraTRACE-0.6.0-win32.msi](https://maxim-s-barabash.github.io/ZebraTrace/download/ZebraTRACE-0.6.0-win32.msi)
 - [ZebraTRACE-0.6.0-amd64.msi](https://maxim-s-barabash.github.io/ZebraTrace/download/ZebraTRACE-0.6.0-amd64.msi)
